spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/youthx_db
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000
