-- YOUTHX V1 Schema Migration
-- Phase 5B-2 — Draft project only (youthx_db_draft)
-- Structure only, no seed data
-- FK creation order per approved Phase 5B-2 spec

-- 1. users
CREATE TABLE users (
    id             UUID PRIMARY KEY,
    email          VARCHAR NOT NULL,
    password_hash  VARCHAR NOT NULL,
    full_name      VARCHAR NOT NULL,
    xp_points      INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_xp_points CHECK (xp_points >= 0)
);

-- 2. expense_categories
CREATE TABLE expense_categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR NOT NULL,
    icon  VARCHAR,

    CONSTRAINT uq_expense_categories_name UNIQUE (name)
);

-- 3. badges
CREATE TABLE badges (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  TEXT,
    icon         VARCHAR
);

-- 4. challenges
CREATE TABLE challenges (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR NOT NULL,
    description TEXT,
    type        VARCHAR NOT NULL,
    xp_reward   INTEGER NOT NULL DEFAULT 0,
    start_date  DATE,
    end_date    DATE,

    CONSTRAINT chk_challenges_type
        CHECK (type IN ('daily','weekly')),
    CONSTRAINT chk_challenges_xp_reward
        CHECK (xp_reward >= 0)
);

-- 5. posts
CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL,
    content     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,

    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX idx_posts_user_created ON posts (user_id, created_at DESC);

-- 6. goals
CREATE TABLE goals (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               UUID NOT NULL,
    name                  VARCHAR NOT NULL,
    category              VARCHAR NOT NULL,
    target_date           DATE,
    progress_percent      INTEGER NOT NULL DEFAULT 0,
    daily_reminder_time   TIME,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ,

    CONSTRAINT fk_goals_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_goals_progress
        CHECK (progress_percent BETWEEN 0 AND 100)
);

-- 7. habits
CREATE TABLE habits (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID NOT NULL,
    name                VARCHAR NOT NULL,
    emoji               VARCHAR,
    color               VARCHAR,
    frequency           VARCHAR NOT NULL,
    time_of_day         TIME,
    current_streak      INTEGER NOT NULL DEFAULT 0,
    last_completed_at   DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_habits_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_habits_streak
        CHECK (current_streak >= 0)
);

-- 8. todos
CREATE TABLE todos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID NOT NULL,
    title          VARCHAR NOT NULL,
    priority       VARCHAR NOT NULL DEFAULT 'medium',
    due_date       DATE,
    is_completed   BOOLEAN NOT NULL DEFAULT false,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT fk_todos_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_todos_priority
        CHECK (priority IN ('high','medium','low'))
);

CREATE INDEX idx_todos_user_due ON todos (user_id, due_date);

-- 9. expenses
CREATE TABLE expenses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID NOT NULL,
    category_id       BIGINT,
    type              VARCHAR NOT NULL,
    amount            NUMERIC(10,2) NOT NULL,
    note              TEXT,
    transaction_date  DATE NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_expenses_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_expenses_category
        FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE RESTRICT,
    CONSTRAINT chk_expenses_type
        CHECK (type IN ('expense','income')),
    CONSTRAINT chk_expenses_amount
        CHECK (amount > 0)
);

-- 10. saving_goals
CREATE TABLE saving_goals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID NOT NULL,
    name            VARCHAR NOT NULL,
    target_amount   NUMERIC(10,2) NOT NULL,
    current_amount  NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_saving_goals_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_saving_goals_target
        CHECK (target_amount > 0),
    CONSTRAINT chk_saving_goals_current
        CHECK (current_amount >= 0)
);

-- 11. post_photos
CREATE TABLE post_photos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id        BIGINT NOT NULL,
    photo_url      VARCHAR NOT NULL,
    display_order  INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_post_photos_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- 12. comments
CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL,
    user_id     UUID NOT NULL,
    content     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

-- 13. likes
CREATE TABLE likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL,
    user_id     UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_likes_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT uq_likes_post_user UNIQUE (post_id, user_id)
);

-- 14. user_badges
CREATE TABLE user_badges (
    user_id    UUID NOT NULL,
    badge_id   BIGINT NOT NULL,
    earned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, badge_id),
    CONSTRAINT fk_user_badges_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_badges_badge
        FOREIGN KEY (badge_id) REFERENCES badges(id) ON DELETE RESTRICT
);

-- 15. user_challenges
CREATE TABLE user_challenges (
    user_id       UUID NOT NULL,
    challenge_id  BIGINT NOT NULL,
    progress      INTEGER NOT NULL DEFAULT 0,
    is_completed  BOOLEAN NOT NULL DEFAULT false,
    completed_at  TIMESTAMPTZ,

    PRIMARY KEY (user_id, challenge_id),
    CONSTRAINT fk_user_challenges_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_challenges_challenge
        FOREIGN KEY (challenge_id) REFERENCES challenges(id) ON DELETE RESTRICT
);
